eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8700/eureka

server:
  port: 8050

spring:
    application:
        name: authentication
    config:
        import: optional:configserver:http://configserver:8888

application:
    config:
        jwt:
            secretkey: 9367566B59703373367639792F423F4528482B4D6251655468576D5A71347435
            expiration: 1800000
