eureka:
    instance:
        hostname: localhost
    client:
        service-url:
            defaultZone: http://localhost:8700/eureka

server:
  port: 8050

spring:
    application:
        name: authentication
    config:
        import: optional:configserver:http://configserver:8888
