version: "3.8"

services:
  mongodb:
    container_name: mongo_db
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - mongo-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoroot
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - microservices

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoroot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - microservices

  mysqldb:
    container_name: mysql_db
    image: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: bloguserdb
      MYSQL_USER: mysqlroot
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - mysql-data:/var/lib/mysql
    networks:
      - microservices

volumes:
  mongo-data: 
  mysql-data:

networks:
  microservices:
  frontend:
